
include: package:flutter_lints/flutter.yaml

linter:

  rules:
     avoid_print: true
     prefer_single_quotes: true
     prefer_const_declarations: true
     always_declare_return_types: true
     always_specify_types: true
     use_key_in_widget_constructors: true
